export const URL = 'https://norma.nomoreparties.space/api';

//export const initialBurger = [];
export const initialBurger = [{
  calories: 420,
  carbohydrates: 53,
  fat: 24,
  image: "https://code.s3.yandex.net/react/code/bun-02.png",
  image_large: "https://code.s3.yandex.net/react/code/bun-02-large.png",
  image_mobile: "https://code.s3.yandex.net/react/code/bun-02-mobile.png",
  name: "Краторная булка N-200i",
  price: 1255,
  proteins: 80,
  type: "bun",
  __v: 0,
  _id: "60d3b41abdacab0026a733c6",
  Id: 0,
},
{
  calories: 643,
  carbohydrates: 85,
  fat: 26,
  image: "https://code.s3.yandex.net/react/code/meat-03.png",
  image_large: "https://code.s3.yandex.net/react/code/meat-03-large.png",
  image_mobile: "https://code.s3.yandex.net/react/code/meat-03-mobile.png",
  name: "Филе Люминесцентного тетраодонтимформа",
  price: 988,
  proteins: 44,
  type: "main",
  __v: 0,
  _id: "60d3b41abdacab0026a733c8",
  Id: 1,
},
{
  calories: 100,
  carbohydrates: 100,
  fat: 99,
  image: "https://code.s3.yandex.net/react/code/sauce-01.png",
  image_large: "https://code.s3.yandex.net/react/code/sauce-01-large.png",
  image_mobile: "https://code.s3.yandex.net/react/code/sauce-01-mobile.png",
  name: "Соус с шипами Антарианского плоскоходца",
  price: 88,
  proteins: 101,
  type: "sauce",
  __v: 0,
  _id: "60d3b41abdacab0026a733cf",
  Id: 2,
}
]

